In [1]:
##creating numpy arrays
import numpy


In [2]:
print(numpy.__version__) ###to check the version of numpy

1.23.5


In [3]:
import pandas

In [4]:
print(pandas.__version__) ## to check the version of pandas

1.5.3


In [5]:
import numpy as np

In [6]:
import pandas as pd

In [7]:
###creating a simple array
[1,2,3,4,5,6,7,8]
np_arr = np.array([1,2,3,4,5,6,7,8])
print (np_arr)

[1 2 3 4 5 6 7 8]


In [8]:
##Performing operations of arrays
#First-adding two arrays
# Creating two arrays of the same shape
arr1 = np.array([1, 2, 3]) # First array
arr2 = np.array([4, 5, 6]) # Second array

# Performing element-wise addition
arr_sum = arr1 + arr2 # Adds corresponding elements in arr1 and arr2
print("Element-wise Addition:", arr_sum)

#Performing element-wise substraction
arr_sub = arr1 - arr2 # Substracts corresponding elements in arr1 and arr2
print("Element-wise Substraction:", arr_sub)

#Performing element-wise multiplication
arr_product = arr1*arr2 # Multiplies corresponding elements in arr1 and arr2
print("Element-wise Multiplication:", arr_product)

#Performing element-wise division
arr_quotient = arr1/arr2 #Divides corresponding elements in arr1 and arr2
print("Element-wise Division:", arr_quotient)

Element-wise Addition: [5 7 9]
Element-wise Substraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


In [9]:
### Array properties
arr = np.array ([1,2,3,4,5,6,7])
print(arr)

D = (arr.ndim) #shows the number of dimesion
print ("The number of dimension is:", D)

S = (arr.shape) #shows the shape of the dimesion
print ("The shape of the array is:", S)

[1 2 3 4 5 6 7]
The number of dimension is: 1
The shape of the array is: (7,)


In [10]:
## Performing Operations on Array

##Accessing elements
print(arr[0]) #this shows the first element
print(arr[4]) #this shows the fifth element


##Slicing arrays
print(arr[0:4]) #this shows the element from index 0 to 3, excluding 4

print (arr[:4]) #you can also write this way if you want to include from beginning

print (arr[3:]) #this shows the element from index 4 to end, excluding 3

1
5
[1 2 3 4]
[1 2 3 4]
[4 5 6 7]


In [11]:
### Basic Structure in Pandas

#Creating a Series
data = [10, 20, 30, 40] #sample data for series
Series = pd.Series(data) #makes sure S is capital letter to create a series from the list
print(Series)

0    10
1    20
2    30
3    40
dtype: int64


In [12]:
#Creating a DataFrame
data_dict = {
    'Name': ['Aashish', 'Bablu', 'Sonu'],  #Name of individuals
    'Age' : ['25', '40', '30'], ###Corresponding ages
    'City' : ['New York', 'Dallas', 'Newark'] # Corresponding cities
}
df = pd.DataFrame(data_dict) #Creating a DataFrame from the dictionary
print("\nPandas DataFrame:")
print (df)


Pandas DataFrame:
      Name Age      City
0  Aashish  25  New York
1    Bablu  40    Dallas
2     Sonu  30    Newark


In [13]:
#Accessing elements in the series
print("The first element in the series:", Series[0])

#Accessing DataFrame columns
print ("\nAccesing the 'Name' column:" )
print (df['Name']) #this displays the name column


#Accessing DataFrame rows using iloc
print("\nAccesing the first row of the DataFrame using iloc:")
print(df.iloc[[0]]) #this displays the first row, 


#just a usage example
print ("\nAccessing the first two rows of the DataFrame using iloc:")
print (df.iloc[0:2]) 

The first element in the series: 10

Accesing the 'Name' column:
0    Aashish
1      Bablu
2       Sonu
Name: Name, dtype: object

Accesing the first row of the DataFrame using iloc:
      Name Age      City
0  Aashish  25  New York

Accessing the first two rows of the DataFrame using iloc:
      Name Age      City
0  Aashish  25  New York
1    Bablu  40    Dallas


In [19]:
#Assigning index to the DataFrame
data = {'Name': ['Aasma', 'Bishal', 'Kajol'],
       'Age': ['22', '29', '35']}
df = pd.DataFrame(data, index = ['a', 'b', 'c'])
print (df)

     Name Age
a   Aasma  22
b  Bishal  29
c   Kajol  35


In [22]:
# Using .loc to select by label
print("\nAccesing the first row of the DataFrame by label")
print(df.loc['a']) # Select row with index label 'a'


Accesing the first row of the DataFrame by label
Name    Aasma
Age        22
Name: a, dtype: object


In [24]:
print(df.loc['a':'b']) ##select rows 'a' to 'b' (inclusive)

     Name Age
a   Aasma  22
b  Bishal  29


In [26]:
print(df.loc['a', 'Name']) #this shows specific value 

Aasma
